
import Header from "@/components/header"
import "./globals.css"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
  }) {
  
  return (
    <html lang="en">
      <body>
        <Header onToggleSidebar={function (): void {
          throw new Error("Function not implemented.");
        } }  />
        
        {children}
      </body>
    </html>
  );
}
